### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by linkoog** [longforus/MvpAutoCodePlus#11]
e: D:\develop-workspaces\workspaces-idea-plugin\MvpAutoCodePlus\src\main\kotlin\com\longforus\mvpautocodeplus\config\ConfigComponent.kt: (30, 36): Cannot choose among the following candidates without completing type inference: 
public fun <T> lazy(initializer: () -> ???): Lazy<???> defined in kotlin
public fun <T> lazy(initializer: () -> ???): Lazy<???> defined in kotlin
e: D:\develop-workspaces\workspaces-idea-plugin\MvpAutoCodePlus\src\main\kotlin\com\longforus\mvpautocodeplus\config\ConfigComponent.kt: (33, 38): Cannot choose among the following candidates without completing type inference: 
public fun <T> lazy(initializer: () -> ???): Lazy<???> defined in kotlin
public fun <T> lazy(initializer: () -> ???): Lazy<???> defined in kotlin
e: D:\develop-workspaces\workspaces-idea-plugin\MvpAutoCodePlus\src\main\kotlin\com\longforus\mvpautocodeplus\config\ConfigComponent.kt: (40, 40): Cannot choose among the following candidates without completing type inference: 
public fun <T> lazy(initializer: () -> ???): Lazy<???> defined in kotlin
public fun <T> lazy(initializer: () -> ???): Lazy<???> defined in kotlin

**Comment by linkoog** [comment]
不会kotlin，不知道怎么搞了

**Comment by longforus** [comment]
@linkoog org.jetbrains.kotlin的依赖有了么?org.jetbrains.ideaIC的依赖有了么?代码有报红么?

**Comment by linkoog** [comment]
> @linkoog org.jetbrains.kotlin的依赖有了么?org.jetbrains.ideaIC的依赖有了么?代码有报红么?

我去掉了compile "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version" 这个依赖，然后就好了

**Comment by longforus** [comment]
@linkoog 可能是有重复依赖 OK
