### ISSUE TITLE
不生成M层代码

### ISSUE THREAD

**Issue by 530l** [longforus/MvpAutoCodePlus#13]
interface IPresenter2<V : ITopView> : ITopPresenter {
    var mView: V?
    fun getContext() = mView?.getCtx()

    @Suppress("UNCHECKED_CAST")
    override fun attachView(view: ITopView) {
        mView = view as V
        mView?.lifecycle?.addObserver(this)
    }

    override fun detachView() {
        mView = null
    }

    //判断是否初始化View
    private val isViewAttached: Boolean
        get() = mView != null

    fun checkViewAttached() {
        if (!isViewAttached) throw MvpViewNotAttachedException()
    }

    private class MvpViewNotAttachedException internal constructor()
        : RuntimeException("Please call IPresenter.attachView(IBaseView) before" + " requesting data to the IPresenter")

}
如果不依赖M层，逻辑网络请求在P层操作，怎样可以让插件不生成M层的类

**Comment by longforus** [comment]
@linyingfa  不勾选 Generate IModel  就好了

**Comment by 530l** [comment]
好像不行，会生成多余的东西，并且各个层的东西也需要手动改继承关系

**Comment by longforus** [comment]
@linyingfa  需要更详细的描述,配置,父类,生成结果等

**Comment by longforus** [comment]
It's been too long ago
