### ISSUE TITLE
hi man ,this plugin is very useful ,can you teach me?

### ISSUE THREAD

**Issue by mouxuefei** [longforus/MvpAutoCodePlus#14]
**Describe the bug**

**Screenshots**
- Plugin config : 

- Package structure :

**Error log**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Win10]
 - Android Studio Version [e.g. 3.1.3]
 - Plugin Version [e.g. 1.1.0]

**Comment by longforus** [comment]
You have a good sense of humor
