### ISSUE TITLE
无法生成presenter和model文件和类

### ISSUE THREAD

**Issue by wbSuperMan** [longforus/MvpAutoCodePlus#16]
在3.5之前的版本都可以生成,升级到3.5之后presenter和model包和类就无法生成了,只能生成view和contract包和下面的类,不知道是不是as3.5修改生成文件的代码?

**Comment by longforus** [comment]
@wenbinAndroid 我在as 3.6版本测试是没有问题的哦,3.5我也一直都是再用的,请注意一下你的配置和生成时的配置.

![1](https://user-images.githubusercontent.com/18444240/75601317-da58e380-5af4-11ea-96a5-9a5e3e2fa8c1.png)
![2](https://user-images.githubusercontent.com/18444240/75601320-dfb62e00-5af4-11ea-8548-6847a4aa551f.png)
注意上面打的勾 
![3](https://user-images.githubusercontent.com/18444240/75601321-e2188800-5af4-11ea-86d2-d6cc5418033b.png)

**Comment by wbSuperMan** [comment]
可以了~将原本的Global模式,改成Current Project就行,3Q

**Comment by longforus** [comment]
不客气
