### ISSUE TITLE
为什么我在presenter中调用model报错 Attempt to invoke interface method 'void com.zy.gank.gankio.mvp.contract.ITodayContract$Model.getTadayInfo()' on a null object reference

### ISSUE THREAD

**Issue by Zaylour** [longforus/MvpAutoCodePlus#7]
`class TodayPresenter : BasePresenterJv<ITodayContract.View, ITodayContract.Model>(), ITodayContract.Presenter {
    override fun createModel(): ITodayContract.Model = TodayModel()//这里实现了抽象方法。
    val myModel: ITodayContract.Model by lazy { TodayModel() }//这是自己声明的。
    override fun TadayInfo() {
        Log.e("ceshi","哈哈哈")
        myModel.getTadayInfo()//这里调用自己声明的就可以用。
        mModel.getTadayInfo()//这里调用生成的mModel来调用就会报错。
        
    }
}`
生成配置那里我用的是基于java的那一套，然后我生成的是kotlin语言的fragment。

**Comment by longforus** [comment]
@Zaylour  在调用了BasePresenterJv:attachView(V) 之后,createModel()方法才会被调用,mModel才会被赋值, BaseMvpFragment类做了一点点修改,你可以看一下

**Comment by Zaylour** [comment]
那BasePresenterJv:attachView(V)在哪里被调用了，在presenter中重写一下就可以了吗
 override fun attachView(view: ITodayContract.View?) {
        super.attachView(view)
    }
有些地方我不怎么懂。

**Comment by longforus** [comment]
@Zaylour 我已经更新了 mvpExample 你可以去看看,打个断点就知道了
